"""hermes_quant.journal.render — Private markdown renderer.

Per ADR-0010 §Decision §8 (Pydantic-only writer): markdown is a function
of SettlementEntry, never authored as raw strings.

Per ADR-0010 §Decision §2: each entry ends with the literal line
`<!-- ENTRY_END -->` so an entry's narrative body can use any markdown
construct without colliding with the separator.

The rendered output is read by humans (operators scrolling the journal)
and parsed by `journal.reader.parse_journal` (round-trip stable).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from .models import AnalystComponent, Reflection, SettlementEntry


ENTRY_DELIM = "<!-- ENTRY_END -->"
JOURNAL_HEADER = """\
# hermes-quant settlement journal

Append-only ledger of trading decisions and their realized outcomes.
Generated by hermes-quant; manual edits will be overwritten on the next
atomic-rename write. See ADR-0010 for the contract.

"""


def render_journal(entries: list[SettlementEntry]) -> str:
    """Render the full journal file from a list of entries.

    Per ADR-0010 §Decision §4: this is what the writer materializes into
    `.tmp` before atomic rename.
    """
    parts = [JOURNAL_HEADER]
    for entry in entries:
        parts.append(_render_entry(entry))
        parts.append(ENTRY_DELIM)
        parts.append("")  # blank line between entries
    return "\n".join(parts)


def _render_entry(entry: SettlementEntry) -> str:
    """Render a single SettlementEntry to its markdown block.

    Format invariants exercised by `tests/unit/test_journal_roundtrip.py`:
    - First line is `## <symbol> <direction-arrow> <summary-tag>`
    - YAML-style fact block delimited by `<!-- META_BEGIN -->` /
      `<!-- META_END -->` (the parser reads from this; everything else
      is decoration)
    """
    lines: list[str] = []

    # Heading line
    arrow = {1: "↑", -1: "↓", 0: "→"}.get(int(entry.direction), "?")
    if entry.is_resolved():
        rr = entry.raw_return or 0.0
        ar = entry.alpha_return or 0.0
        hm = entry.hold_minutes or 0
        tag = f"[{rr:+.2%} raw / {ar:+.2%} alpha / {hm}m]"
    elif entry.hitl_kind == "reject":
        tag = "[rejected]"
    elif entry.hitl_kind == "expire":
        tag = "[expired]"
    elif entry.hitl_kind == "approve":
        tag = "[approved-pending-settlement]"
    else:
        tag = "[pending]"
    lines.append(f"## {entry.symbol} {arrow} {tag}")
    lines.append("")

    # Machine-readable meta block (the parser's anchor)
    lines.append("<!-- META_BEGIN -->")
    lines.append(f"entry_id: {entry.entry_id}")
    lines.append(f"asof_decision: {_iso(entry.asof_decision)}")
    lines.append(f"asset_class: {entry.asset_class}")
    lines.append(f"direction: {int(entry.direction)}")
    lines.append(f"confidence: {entry.confidence:.4f}")
    lines.append(f"target_position_pct: {entry.target_position_pct:+.4f}")
    lines.append(f"decision_price: {entry.decision_price:.6f}")
    lines.append(f"benchmark_symbol: {entry.benchmark_symbol}")
    if entry.is_resolved():
        lines.append(f"asof_settlement: {_iso(entry.asof_settlement)}")
        lines.append(f"exit_price: {entry.exit_price:.6f}")
        lines.append(f"raw_return: {entry.raw_return:.6f}")
        lines.append(f"alpha_return: {entry.alpha_return:.6f}")
        lines.append(f"hold_minutes: {entry.hold_minutes}")
        if entry.reflection is not None:
            lines.append(f"reflection_thesis_held: {entry.reflection.thesis_held}")
            lines.append(f"reflection_magnitude_error: {entry.reflection.magnitude_error:.4f}")
            lines.append(f"reflection_rule_version: {entry.reflection.rule_version}")
    if entry.hitl_kind:
        lines.append(f"hitl_kind: {entry.hitl_kind}")
        if entry.hitl_reason:
            lines.append(f"hitl_reason: {_one_line(entry.hitl_reason)}")
        if entry.hitl_approver:
            lines.append(f"hitl_approver: {entry.hitl_approver}")
    lines.append("<!-- META_END -->")
    lines.append("")

    # Narrative
    lines.append(f"**Reason**: {entry.reason}")
    lines.append("")

    # Per-analyst components
    if entry.per_analyst_components:
        lines.append("**Components**:")
        for c in entry.per_analyst_components:
            d_arrow = {1: "↑", -1: "↓", 0: "→"}.get(int(c.direction), "?")
            lines.append(f"- `{c.analyst}` {d_arrow} conf={c.confidence:.2f} weight={c.weight:.2f}")
        lines.append("")

    # Reflection narrative (Phase B)
    if entry.reflection is not None:
        lines.append(
            f"**Reflection** ({entry.reflection.rule_version}): "
            f"thesis_held={entry.reflection.thesis_held}, "
            f"magnitude_error={entry.reflection.magnitude_error:.2f}×"
        )
        lines.append("")

    return "\n".join(lines)


def _iso(dt: Any) -> str:
    """Render a datetime as ISO 8601 UTC seconds. Tolerates string passthrough."""
    if dt is None:
        return ""
    if isinstance(dt, str):
        return dt
    if isinstance(dt, datetime):
        if dt.tzinfo is None:
            return dt.strftime("%Y-%m-%dT%H:%M:%SZ")
        return dt.strftime("%Y-%m-%dT%H:%M:%S%z")
    return str(dt)


def _one_line(s: str) -> str:
    """Collapse newlines so the meta block stays one-fact-per-line."""
    return s.replace("\n", " ").replace("\r", " ")
